package main

const (
	TITLE = "ProGo Bird"

	WINDOW_W = 1024
	WINDOW_H = 768

	SCENARIO_W     = 300
	SCENARIO_H     = 230
	SCENARIO_MAP_W = SCENARIO_W * 4

	CHAR_W         = 36
	CHAR_H         = 26
	CHAR_GRAV_INIT = 0
	CHAR_GRAV      = -256
	CHAR_RUNSPEED  = 64
	CHAR_JUMPSPEED = 192

	TIME_AGENT_FACTOR  = 0.50
	START_AGENT_FACTOR = 4

	PLATFORM_MARGIN_H  = 18
	PLATFORM_MARGIN_V  = 0
	PLATFORM_TB_MARGIN = 0
)
